### ISSUE TITLE
Java development example doesn't work

### ISSUE THREAD

**Issue by ethernet8023** [Open-RIO/HotPlate#3]
Following the instructions in the Wiki, after generating an IDEA project file, a Gradle module simulation build fails with the following error:
Exception in thread "main" java.lang.ClassNotFoundException: jaci.openrio.toast.core.ToastBootstrap
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:264)

**Comment by ethernet8023** [comment]
Whoops, wrong repo.
